
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU3NjcxODUyOH0.JEHb2Boph225a4ml6WMJCZfONn5EeOf6_l7SK9bC4XY

###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU3NjcxODUyOH0.JEHb2Boph225a4ml6WMJCZfONn5EeOf6_l7SK9bC4XY

{
    "username": "nuevo usuario"
}

###
GET http://localhost:3000/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU3NjcxODUyOH0.JEHb2Boph225a4ml6WMJCZfONn5EeOf6_l7SK9bC4XY

###
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU3NjcxODUyOH0.JEHb2Boph225a4ml6WMJCZfONn5EeOf6_l7SK9bC4XY

{
    "name": "team 1"
}